# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy WAR app to Azure Web App - rabotynet

on:
  push:
    branches:
      - development

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '8'

    - name: Build with Maven
      run: mvn clean install

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'rabotynet'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_95baf474193b4f3fac48976774eccd1d }}
        package: '${{ github.workspace }}/target/*.war'